name: Download Fontstruct Font

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download-font:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Pull latest changes
        run: git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip chromium-browser chromium-chromedriver
          python -m pip install --upgrade pip
          pip install selenium requests

      - name: Run fontstruct download script
        run: python scripts/fontstruct.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update font from Fontstruct" || echo "No changes to commit"
          git push origin main
