name: Save Aternos State

on:
  workflow_dispatch:

jobs:
  save-state:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          pip install playwright
          playwright install --with-deps chromium

      - name: Run Playwright Script
        env:
          ATER_USERNAME: ${{ secrets.ATER_USERNAME }}
          ATER_PASSWORD: ${{ secrets.ATER_PASSWORD }}
        run: |
          xvfb-run --auto-servernum python save_state.py

      - name: Commit state.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add aternos_state.json
          git commit -m "Update state.json"
          git push
